/*
 * one_msg_waba_sdk
 * [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter 'token' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All 'send' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: hello@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Commerce;
import org.openapitools.client.model.GetMe401Response;
import org.openapitools.client.model.SendMessageStatus;
import org.openapitools.client.model.SendProductRequest;
import org.openapitools.client.model.SetCommerce;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsCatalogsApi
 */
@Disabled
public class ProductsCatalogsApiTest {

    private final ProductsCatalogsApi api = new ProductsCatalogsApi();

    /**
     * Send a Product
     *
     * Send a single product or product list to a new or existing chat. (Only if the dialogue has an Open Session). Only one of two parameters is needed to determine the destination - chatId or phone.  First, you need to upload your inventory to Facebook. You can use the API or Facebook’s Commerce Manager to do that. If you already have a Facebook catalog set up, we suggest that you leverage that catalog for WhatsApp commerce use cases.  **You can not send products to Business WhatsApp clients.**
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendProductTest() throws ApiException {
        SendProductRequest sendProductRequest = null;
        SendMessageStatus response = api.sendProduct(sendProductRequest);
        // TODO: test validations
    }

    /**
     * Set Commerce Settings
     *
     * **is_catalog_visible** - Set to true to show catalog storefront icon or false to hide it. **is_cart_enabled** - Set to true to enable cart or false to disable it.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setCommerceTest() throws ApiException {
        Commerce commerce = null;
        SetCommerce response = api.setCommerce(commerce);
        // TODO: test validations
    }

}
