# coding: utf-8

"""
    one_msg_waba_sdk

    [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter 'token' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All 'send' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail

    The version of the OpenAPI document: 2.39.0
    Contact: hello@1msg.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TemplateLanguageProp(str, Enum):
    """
    Template language
    """

    """
    allowed enum values
    """
    AF = 'af'
    SQ = 'sq'
    AR = 'ar'
    AZ = 'az'
    BN = 'bn'
    BG = 'bg'
    CA = 'ca'
    ZH_CN = 'zh_CN'
    ZH_HK = 'zh_HK'
    ZH_TW = 'zh_TW'
    HR = 'hr'
    CS = 'cs'
    DA = 'da'
    NL = 'nl'
    EN = 'en'
    EN_GB = 'en_GB'
    EN_US = 'en_US'
    ET = 'et'
    FIL = 'fil'
    FI = 'fi'
    FR = 'fr'
    DE = 'de'
    EL = 'el'
    GU = 'gu'
    HE = 'he'
    HI = 'hi'
    HU = 'hu'
    ID = 'id'
    GA = 'ga'
    IT = 'it'
    JA = 'ja'
    KN = 'kn'
    KK = 'kk'
    KO = 'ko'
    LO = 'lo'
    LV = 'lv'
    LT = 'lt'
    MK = 'mk'
    MS = 'ms'
    MR = 'mr'
    NB = 'nb'
    FA = 'fa'
    PL = 'pl'
    PT_BR = 'pt_BR'
    PT_PT = 'pt_PT'
    PA = 'pa'
    RO = 'ro'
    RU = 'ru'
    SR = 'sr'
    SK = 'sk'
    SL = 'sl'
    ES = 'es'
    ES_AR = 'es_AR'
    ES_ES = 'es_ES'
    ES_MX = 'es_MX'
    SW = 'sw'
    SV = 'sv'
    TA = 'ta'
    TE = 'te'
    TH = 'th'
    TR = 'tr'
    UK = 'uk'
    UR = 'ur'
    UZ = 'uz'
    VI = 'vi'

    @classmethod
    def from_json(cls, json_str: str) -> TemplateLanguageProp:
        """Create an instance of TemplateLanguageProp from a JSON string"""
        return TemplateLanguageProp(json.loads(json_str))


