/* tslint:disable */
/* eslint-disable */
/**
 * one_msg_waba_sdk
 * [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter \'token\' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All \'send\' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: hello@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SendListRequestAllOfRows } from './SendListRequestAllOfRows';
import {
    SendListRequestAllOfRowsFromJSON,
    SendListRequestAllOfRowsFromJSONTyped,
    SendListRequestAllOfRowsToJSON,
} from './SendListRequestAllOfRows';

/**
 * 
 * @export
 * @interface SendListRequestAllOfSections
 */
export interface SendListRequestAllOfSections {
    /**
     * Title of section, up to 24 symbols. Required if there are more then 1 section
     * @type {string}
     * @memberof SendListRequestAllOfSections
     */
    title?: string;
    /**
     * 
     * @type {Array<SendListRequestAllOfRows>}
     * @memberof SendListRequestAllOfSections
     */
    rows: Array<SendListRequestAllOfRows>;
}

/**
 * Check if a given object implements the SendListRequestAllOfSections interface.
 */
export function instanceOfSendListRequestAllOfSections(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rows" in value;

    return isInstance;
}

export function SendListRequestAllOfSectionsFromJSON(json: any): SendListRequestAllOfSections {
    return SendListRequestAllOfSectionsFromJSONTyped(json, false);
}

export function SendListRequestAllOfSectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendListRequestAllOfSections {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'rows': ((json['rows'] as Array<any>).map(SendListRequestAllOfRowsFromJSON)),
    };
}

export function SendListRequestAllOfSectionsToJSON(value?: SendListRequestAllOfSections | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'rows': ((value.rows as Array<any>).map(SendListRequestAllOfRowsToJSON)),
    };
}

