/* tslint:disable */
/* eslint-disable */
/**
 * one_msg_waba_sdk
 * [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter \'token\' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All \'send\' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: hello@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SetSettings200ResponseAllOfUpdate } from './SetSettings200ResponseAllOfUpdate';
import {
    SetSettings200ResponseAllOfUpdateFromJSON,
    SetSettings200ResponseAllOfUpdateFromJSONTyped,
    SetSettings200ResponseAllOfUpdateToJSON,
} from './SetSettings200ResponseAllOfUpdate';

/**
 * 
 * @export
 * @interface SetSettings200Response
 */
export interface SetSettings200Response {
    /**
     * 
     * @type {string}
     * @memberof SetSettings200Response
     */
    webhookUrl?: string | null;
    /**
     * 
     * @type {SetSettings200ResponseAllOfUpdate}
     * @memberof SetSettings200Response
     */
    update: SetSettings200ResponseAllOfUpdate;
}

/**
 * Check if a given object implements the SetSettings200Response interface.
 */
export function instanceOfSetSettings200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "update" in value;

    return isInstance;
}

export function SetSettings200ResponseFromJSON(json: any): SetSettings200Response {
    return SetSettings200ResponseFromJSONTyped(json, false);
}

export function SetSettings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetSettings200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'webhookUrl': !exists(json, 'webhookUrl') ? undefined : json['webhookUrl'],
        'update': SetSettings200ResponseAllOfUpdateFromJSON(json['update']),
    };
}

export function SetSettings200ResponseToJSON(value?: SetSettings200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'webhookUrl': value.webhookUrl,
        'update': SetSettings200ResponseAllOfUpdateToJSON(value.update),
    };
}

