/**
 * one_msg_waba_sdk
 * [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter 'token' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All 'send' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: hello@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.0.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/AddTemplateRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



AddTemplateRequest::AddTemplateRequest()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_CategoryIsSet = false;
    m_ComponentsIsSet = false;
    m_LanguageIsSet = false;
}

AddTemplateRequest::~AddTemplateRequest()
{
}

void AddTemplateRequest::validate()
{
    // TODO: implement validation
}

web::json::value AddTemplateRequest::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_CategoryIsSet)
    {
        val[utility::conversions::to_string_t(U("category"))] = ModelBase::toJson(m_Category);
    }
    if(m_ComponentsIsSet)
    {
        val[utility::conversions::to_string_t(U("components"))] = ModelBase::toJson(m_Components);
    }
    if(m_LanguageIsSet)
    {
        val[utility::conversions::to_string_t(U("language"))] = ModelBase::toJson(m_Language);
    }

    return val;
}

bool AddTemplateRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("category"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("category")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<TemplateCategoryProp> refVal_setCategory;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCategory);
            setCategory(refVal_setCategory);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("components"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("components")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<TemplateComponentsProp> refVal_setComponents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setComponents);
            setComponents(refVal_setComponents);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("language"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("language")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<TemplateLanguageProp> refVal_setLanguage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLanguage);
            setLanguage(refVal_setLanguage);
        }
    }
    return ok;
}

void AddTemplateRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_CategoryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("category")), m_Category));
    }
    if(m_ComponentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("components")), m_Components));
    }
    if(m_LanguageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("language")), m_Language));
    }
}

bool AddTemplateRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("category"))))
    {
        std::shared_ptr<TemplateCategoryProp> refVal_setCategory;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("category"))), refVal_setCategory );
        setCategory(refVal_setCategory);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("components"))))
    {
        std::shared_ptr<TemplateComponentsProp> refVal_setComponents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("components"))), refVal_setComponents );
        setComponents(refVal_setComponents);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("language"))))
    {
        std::shared_ptr<TemplateLanguageProp> refVal_setLanguage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("language"))), refVal_setLanguage );
        setLanguage(refVal_setLanguage);
    }
    return ok;
}

utility::string_t AddTemplateRequest::getName() const
{
    return m_Name;
}

void AddTemplateRequest::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool AddTemplateRequest::nameIsSet() const
{
    return m_NameIsSet;
}

void AddTemplateRequest::unsetName()
{
    m_NameIsSet = false;
}
std::shared_ptr<TemplateCategoryProp> AddTemplateRequest::getCategory() const
{
    return m_Category;
}

void AddTemplateRequest::setCategory(const std::shared_ptr<TemplateCategoryProp>& value)
{
    m_Category = value;
    m_CategoryIsSet = true;
}

bool AddTemplateRequest::categoryIsSet() const
{
    return m_CategoryIsSet;
}

void AddTemplateRequest::unsetCategory()
{
    m_CategoryIsSet = false;
}
std::shared_ptr<TemplateComponentsProp> AddTemplateRequest::getComponents() const
{
    return m_Components;
}

void AddTemplateRequest::setComponents(const std::shared_ptr<TemplateComponentsProp>& value)
{
    m_Components = value;
    m_ComponentsIsSet = true;
}

bool AddTemplateRequest::componentsIsSet() const
{
    return m_ComponentsIsSet;
}

void AddTemplateRequest::unsetComponents()
{
    m_ComponentsIsSet = false;
}
std::shared_ptr<TemplateLanguageProp> AddTemplateRequest::getLanguage() const
{
    return m_Language;
}

void AddTemplateRequest::setLanguage(const std::shared_ptr<TemplateLanguageProp>& value)
{
    m_Language = value;
    m_LanguageIsSet = true;
}

bool AddTemplateRequest::languageIsSet() const
{
    return m_LanguageIsSet;
}

void AddTemplateRequest::unsetLanguage()
{
    m_LanguageIsSet = false;
}
}
}
}
}


