/**
 * one_msg_waba_sdk
 * [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter 'token' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All 'send' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: hello@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.0.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ContactsRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



ContactsRequest::ContactsRequest()
{
    m_Blocking = utility::conversions::to_string_t("");
    m_BlockingIsSet = false;
    m_Force_check = false;
    m_Force_checkIsSet = false;
    m_ContactsIsSet = false;
}

ContactsRequest::~ContactsRequest()
{
}

void ContactsRequest::validate()
{
    // TODO: implement validation
}

web::json::value ContactsRequest::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_BlockingIsSet)
    {
        val[utility::conversions::to_string_t(U("blocking"))] = ModelBase::toJson(m_Blocking);
    }
    if(m_Force_checkIsSet)
    {
        val[utility::conversions::to_string_t(U("force_check"))] = ModelBase::toJson(m_Force_check);
    }
    if(m_ContactsIsSet)
    {
        val[utility::conversions::to_string_t(U("contacts"))] = ModelBase::toJson(m_Contacts);
    }

    return val;
}

bool ContactsRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("blocking"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("blocking")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBlocking;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBlocking);
            setBlocking(refVal_setBlocking);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("force_check"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("force_check")));
        if(!fieldValue.is_null())
        {
            bool refVal_setForceCheck;
            ok &= ModelBase::fromJson(fieldValue, refVal_setForceCheck);
            setForceCheck(refVal_setForceCheck);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("contacts"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("contacts")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setContacts;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContacts);
            setContacts(refVal_setContacts);
        }
    }
    return ok;
}

void ContactsRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_BlockingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("blocking")), m_Blocking));
    }
    if(m_Force_checkIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("force_check")), m_Force_check));
    }
    if(m_ContactsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("contacts")), m_Contacts));
    }
}

bool ContactsRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("blocking"))))
    {
        utility::string_t refVal_setBlocking;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("blocking"))), refVal_setBlocking );
        setBlocking(refVal_setBlocking);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("force_check"))))
    {
        bool refVal_setForceCheck;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("force_check"))), refVal_setForceCheck );
        setForceCheck(refVal_setForceCheck);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("contacts"))))
    {
        std::vector<utility::string_t> refVal_setContacts;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("contacts"))), refVal_setContacts );
        setContacts(refVal_setContacts);
    }
    return ok;
}

utility::string_t ContactsRequest::getBlocking() const
{
    return m_Blocking;
}

void ContactsRequest::setBlocking(const utility::string_t& value)
{
    m_Blocking = value;
    m_BlockingIsSet = true;
}

bool ContactsRequest::blockingIsSet() const
{
    return m_BlockingIsSet;
}

void ContactsRequest::unsetBlocking()
{
    m_BlockingIsSet = false;
}
bool ContactsRequest::isForceCheck() const
{
    return m_Force_check;
}

void ContactsRequest::setForceCheck(bool value)
{
    m_Force_check = value;
    m_Force_checkIsSet = true;
}

bool ContactsRequest::forceCheckIsSet() const
{
    return m_Force_checkIsSet;
}

void ContactsRequest::unsetForce_check()
{
    m_Force_checkIsSet = false;
}
std::vector<utility::string_t>& ContactsRequest::getContacts()
{
    return m_Contacts;
}

void ContactsRequest::setContacts(const std::vector<utility::string_t>& value)
{
    m_Contacts = value;
    m_ContactsIsSet = true;
}

bool ContactsRequest::contactsIsSet() const
{
    return m_ContactsIsSet;
}

void ContactsRequest::unsetContacts()
{
    m_ContactsIsSet = false;
}
}
}
}
}


