/*
 * add_template_request.h
 *
 * 
 */

#ifndef _add_template_request_H_
#define _add_template_request_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct add_template_request_t add_template_request_t;

#include "template_category_prop.h"
#include "template_components_prop.h"
#include "template_language_prop.h"

// Enum  for add_template_request

typedef enum  { one_msg_waba_sdk_add_template_request__NULL = 0, one_msg_waba_sdk_add_template_request__MARKETING, one_msg_waba_sdk_add_template_request__TRANSACTIONAL, one_msg_waba_sdk_add_template_request__OTP } one_msg_waba_sdk_add_template_request__e;

char* add_template_request_category_ToString(one_msg_waba_sdk_add_template_request__e category);

one_msg_waba_sdk_add_template_request__e add_template_request_category_FromString(char* category);

// Enum  for add_template_request

typedef enum  { one_msg_waba_sdk_add_template_request__NULL = 0, one_msg_waba_sdk_add_template_request__af, one_msg_waba_sdk_add_template_request__sq, one_msg_waba_sdk_add_template_request__ar, one_msg_waba_sdk_add_template_request__az, one_msg_waba_sdk_add_template_request__bn, one_msg_waba_sdk_add_template_request__bg, one_msg_waba_sdk_add_template_request__ca, one_msg_waba_sdk_add_template_request__zh_CN, one_msg_waba_sdk_add_template_request__zh_HK, one_msg_waba_sdk_add_template_request__zh_TW, one_msg_waba_sdk_add_template_request__hr, one_msg_waba_sdk_add_template_request__cs, one_msg_waba_sdk_add_template_request__da, one_msg_waba_sdk_add_template_request__nl, one_msg_waba_sdk_add_template_request__en, one_msg_waba_sdk_add_template_request__en_GB, one_msg_waba_sdk_add_template_request__en_US, one_msg_waba_sdk_add_template_request__et, one_msg_waba_sdk_add_template_request__fil, one_msg_waba_sdk_add_template_request__fi, one_msg_waba_sdk_add_template_request__fr, one_msg_waba_sdk_add_template_request__de, one_msg_waba_sdk_add_template_request__el, one_msg_waba_sdk_add_template_request__gu, one_msg_waba_sdk_add_template_request__he, one_msg_waba_sdk_add_template_request__hi, one_msg_waba_sdk_add_template_request__hu, one_msg_waba_sdk_add_template_request__id, one_msg_waba_sdk_add_template_request__ga, one_msg_waba_sdk_add_template_request__it, one_msg_waba_sdk_add_template_request__ja, one_msg_waba_sdk_add_template_request__kn, one_msg_waba_sdk_add_template_request__kk, one_msg_waba_sdk_add_template_request__ko, one_msg_waba_sdk_add_template_request__lo, one_msg_waba_sdk_add_template_request__lv, one_msg_waba_sdk_add_template_request__lt, one_msg_waba_sdk_add_template_request__mk, one_msg_waba_sdk_add_template_request__ms, one_msg_waba_sdk_add_template_request__mr, one_msg_waba_sdk_add_template_request__nb, one_msg_waba_sdk_add_template_request__fa, one_msg_waba_sdk_add_template_request__pl, one_msg_waba_sdk_add_template_request__pt_BR, one_msg_waba_sdk_add_template_request__pt_PT, one_msg_waba_sdk_add_template_request__pa, one_msg_waba_sdk_add_template_request__ro, one_msg_waba_sdk_add_template_request__ru, one_msg_waba_sdk_add_template_request__sr, one_msg_waba_sdk_add_template_request__sk, one_msg_waba_sdk_add_template_request__sl, one_msg_waba_sdk_add_template_request__es, one_msg_waba_sdk_add_template_request__es_AR, one_msg_waba_sdk_add_template_request__es_ES, one_msg_waba_sdk_add_template_request__es_MX, one_msg_waba_sdk_add_template_request__sw, one_msg_waba_sdk_add_template_request__sv, one_msg_waba_sdk_add_template_request__ta, one_msg_waba_sdk_add_template_request__te, one_msg_waba_sdk_add_template_request__th, one_msg_waba_sdk_add_template_request__tr, one_msg_waba_sdk_add_template_request__uk, one_msg_waba_sdk_add_template_request__ur, one_msg_waba_sdk_add_template_request__uz, one_msg_waba_sdk_add_template_request__vi } one_msg_waba_sdk_add_template_request__e;

char* add_template_request_language_ToString(one_msg_waba_sdk_add_template_request__e language);

one_msg_waba_sdk_add_template_request__e add_template_request_language_FromString(char* language);



typedef struct add_template_request_t {
    char *name; // string
    template_category_prop_t *category; // custom
    template_components_prop_t *components; // custom
    template_language_prop_t *language; // custom

} add_template_request_t;

add_template_request_t *add_template_request_create(
    char *name,
    template_category_prop_t *category,
    template_components_prop_t *components,
    template_language_prop_t *language
);

void add_template_request_free(add_template_request_t *add_template_request);

add_template_request_t *add_template_request_parseFromJSON(cJSON *add_template_requestJSON);

cJSON *add_template_request_convertToJSON(add_template_request_t *add_template_request);

#endif /* _add_template_request_H_ */

