/*
 * send_template_request_all_of_language.h
 *
 * Object, containing fields \&quot;policy\&quot; and \&quot;code\&quot;.  **policy** - now \&quot;deterministic\&quot; is only available option;  **code** - one of supported language codes
 */

#ifndef _send_template_request_all_of_language_H_
#define _send_template_request_all_of_language_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct send_template_request_all_of_language_t send_template_request_all_of_language_t;

#include "template_language_prop.h"

// Enum POLICY for send_template_request_all_of_language

typedef enum  { one_msg_waba_sdk_send_template_request_all_of_language_POLICY_NULL = 0, one_msg_waba_sdk_send_template_request_all_of_language_POLICY_deterministic } one_msg_waba_sdk_send_template_request_all_of_language_POLICY_e;

char* send_template_request_all_of_language_policy_ToString(one_msg_waba_sdk_send_template_request_all_of_language_POLICY_e policy);

one_msg_waba_sdk_send_template_request_all_of_language_POLICY_e send_template_request_all_of_language_policy_FromString(char* policy);

// Enum  for send_template_request_all_of_language

typedef enum  { one_msg_waba_sdk_send_template_request_all_of_language__NULL = 0, one_msg_waba_sdk_send_template_request_all_of_language__af, one_msg_waba_sdk_send_template_request_all_of_language__sq, one_msg_waba_sdk_send_template_request_all_of_language__ar, one_msg_waba_sdk_send_template_request_all_of_language__az, one_msg_waba_sdk_send_template_request_all_of_language__bn, one_msg_waba_sdk_send_template_request_all_of_language__bg, one_msg_waba_sdk_send_template_request_all_of_language__ca, one_msg_waba_sdk_send_template_request_all_of_language__zh_CN, one_msg_waba_sdk_send_template_request_all_of_language__zh_HK, one_msg_waba_sdk_send_template_request_all_of_language__zh_TW, one_msg_waba_sdk_send_template_request_all_of_language__hr, one_msg_waba_sdk_send_template_request_all_of_language__cs, one_msg_waba_sdk_send_template_request_all_of_language__da, one_msg_waba_sdk_send_template_request_all_of_language__nl, one_msg_waba_sdk_send_template_request_all_of_language__en, one_msg_waba_sdk_send_template_request_all_of_language__en_GB, one_msg_waba_sdk_send_template_request_all_of_language__en_US, one_msg_waba_sdk_send_template_request_all_of_language__et, one_msg_waba_sdk_send_template_request_all_of_language__fil, one_msg_waba_sdk_send_template_request_all_of_language__fi, one_msg_waba_sdk_send_template_request_all_of_language__fr, one_msg_waba_sdk_send_template_request_all_of_language__de, one_msg_waba_sdk_send_template_request_all_of_language__el, one_msg_waba_sdk_send_template_request_all_of_language__gu, one_msg_waba_sdk_send_template_request_all_of_language__he, one_msg_waba_sdk_send_template_request_all_of_language__hi, one_msg_waba_sdk_send_template_request_all_of_language__hu, one_msg_waba_sdk_send_template_request_all_of_language__id, one_msg_waba_sdk_send_template_request_all_of_language__ga, one_msg_waba_sdk_send_template_request_all_of_language__it, one_msg_waba_sdk_send_template_request_all_of_language__ja, one_msg_waba_sdk_send_template_request_all_of_language__kn, one_msg_waba_sdk_send_template_request_all_of_language__kk, one_msg_waba_sdk_send_template_request_all_of_language__ko, one_msg_waba_sdk_send_template_request_all_of_language__lo, one_msg_waba_sdk_send_template_request_all_of_language__lv, one_msg_waba_sdk_send_template_request_all_of_language__lt, one_msg_waba_sdk_send_template_request_all_of_language__mk, one_msg_waba_sdk_send_template_request_all_of_language__ms, one_msg_waba_sdk_send_template_request_all_of_language__mr, one_msg_waba_sdk_send_template_request_all_of_language__nb, one_msg_waba_sdk_send_template_request_all_of_language__fa, one_msg_waba_sdk_send_template_request_all_of_language__pl, one_msg_waba_sdk_send_template_request_all_of_language__pt_BR, one_msg_waba_sdk_send_template_request_all_of_language__pt_PT, one_msg_waba_sdk_send_template_request_all_of_language__pa, one_msg_waba_sdk_send_template_request_all_of_language__ro, one_msg_waba_sdk_send_template_request_all_of_language__ru, one_msg_waba_sdk_send_template_request_all_of_language__sr, one_msg_waba_sdk_send_template_request_all_of_language__sk, one_msg_waba_sdk_send_template_request_all_of_language__sl, one_msg_waba_sdk_send_template_request_all_of_language__es, one_msg_waba_sdk_send_template_request_all_of_language__es_AR, one_msg_waba_sdk_send_template_request_all_of_language__es_ES, one_msg_waba_sdk_send_template_request_all_of_language__es_MX, one_msg_waba_sdk_send_template_request_all_of_language__sw, one_msg_waba_sdk_send_template_request_all_of_language__sv, one_msg_waba_sdk_send_template_request_all_of_language__ta, one_msg_waba_sdk_send_template_request_all_of_language__te, one_msg_waba_sdk_send_template_request_all_of_language__th, one_msg_waba_sdk_send_template_request_all_of_language__tr, one_msg_waba_sdk_send_template_request_all_of_language__uk, one_msg_waba_sdk_send_template_request_all_of_language__ur, one_msg_waba_sdk_send_template_request_all_of_language__uz, one_msg_waba_sdk_send_template_request_all_of_language__vi } one_msg_waba_sdk_send_template_request_all_of_language__e;

char* send_template_request_all_of_language_code_ToString(one_msg_waba_sdk_send_template_request_all_of_language__e code);

one_msg_waba_sdk_send_template_request_all_of_language__e send_template_request_all_of_language_code_FromString(char* code);



typedef struct send_template_request_all_of_language_t {
    one_msg_waba_sdk_send_template_request_all_of_language_POLICY_e policy; //enum
    template_language_prop_t *code; // custom

} send_template_request_all_of_language_t;

send_template_request_all_of_language_t *send_template_request_all_of_language_create(
    one_msg_waba_sdk_send_template_request_all_of_language_POLICY_e policy,
    template_language_prop_t *code
);

void send_template_request_all_of_language_free(send_template_request_all_of_language_t *send_template_request_all_of_language);

send_template_request_all_of_language_t *send_template_request_all_of_language_parseFromJSON(cJSON *send_template_request_all_of_languageJSON);

cJSON *send_template_request_all_of_language_convertToJSON(send_template_request_all_of_language_t *send_template_request_all_of_language);

#endif /* _send_template_request_all_of_language_H_ */

