/*
 * template_language_prop.h
 *
 * Template language
 */

#ifndef _template_language_prop_H_
#define _template_language_prop_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct template_language_prop_t template_language_prop_t;


// Enum  for template_language_prop

typedef enum { one_msg_waba_sdk_template_language_prop__NULL = 0, one_msg_waba_sdk_template_language_prop__af, one_msg_waba_sdk_template_language_prop__sq, one_msg_waba_sdk_template_language_prop__ar, one_msg_waba_sdk_template_language_prop__az, one_msg_waba_sdk_template_language_prop__bn, one_msg_waba_sdk_template_language_prop__bg, one_msg_waba_sdk_template_language_prop__ca, one_msg_waba_sdk_template_language_prop__zh_CN, one_msg_waba_sdk_template_language_prop__zh_HK, one_msg_waba_sdk_template_language_prop__zh_TW, one_msg_waba_sdk_template_language_prop__hr, one_msg_waba_sdk_template_language_prop__cs, one_msg_waba_sdk_template_language_prop__da, one_msg_waba_sdk_template_language_prop__nl, one_msg_waba_sdk_template_language_prop__en, one_msg_waba_sdk_template_language_prop__en_GB, one_msg_waba_sdk_template_language_prop__en_US, one_msg_waba_sdk_template_language_prop__et, one_msg_waba_sdk_template_language_prop__fil, one_msg_waba_sdk_template_language_prop__fi, one_msg_waba_sdk_template_language_prop__fr, one_msg_waba_sdk_template_language_prop__de, one_msg_waba_sdk_template_language_prop__el, one_msg_waba_sdk_template_language_prop__gu, one_msg_waba_sdk_template_language_prop__he, one_msg_waba_sdk_template_language_prop__hi, one_msg_waba_sdk_template_language_prop__hu, one_msg_waba_sdk_template_language_prop__id, one_msg_waba_sdk_template_language_prop__ga, one_msg_waba_sdk_template_language_prop__it, one_msg_waba_sdk_template_language_prop__ja, one_msg_waba_sdk_template_language_prop__kn, one_msg_waba_sdk_template_language_prop__kk, one_msg_waba_sdk_template_language_prop__ko, one_msg_waba_sdk_template_language_prop__lo, one_msg_waba_sdk_template_language_prop__lv, one_msg_waba_sdk_template_language_prop__lt, one_msg_waba_sdk_template_language_prop__mk, one_msg_waba_sdk_template_language_prop__ms, one_msg_waba_sdk_template_language_prop__mr, one_msg_waba_sdk_template_language_prop__nb, one_msg_waba_sdk_template_language_prop__fa, one_msg_waba_sdk_template_language_prop__pl, one_msg_waba_sdk_template_language_prop__pt_BR, one_msg_waba_sdk_template_language_prop__pt_PT, one_msg_waba_sdk_template_language_prop__pa, one_msg_waba_sdk_template_language_prop__ro, one_msg_waba_sdk_template_language_prop__ru, one_msg_waba_sdk_template_language_prop__sr, one_msg_waba_sdk_template_language_prop__sk, one_msg_waba_sdk_template_language_prop__sl, one_msg_waba_sdk_template_language_prop__es, one_msg_waba_sdk_template_language_prop__es_AR, one_msg_waba_sdk_template_language_prop__es_ES, one_msg_waba_sdk_template_language_prop__es_MX, one_msg_waba_sdk_template_language_prop__sw, one_msg_waba_sdk_template_language_prop__sv, one_msg_waba_sdk_template_language_prop__ta, one_msg_waba_sdk_template_language_prop__te, one_msg_waba_sdk_template_language_prop__th, one_msg_waba_sdk_template_language_prop__tr, one_msg_waba_sdk_template_language_prop__uk, one_msg_waba_sdk_template_language_prop__ur, one_msg_waba_sdk_template_language_prop__uz, one_msg_waba_sdk_template_language_prop__vi } one_msg_waba_sdk_template_language_prop__e;

char* template_language_prop_template_language_prop_ToString(one_msg_waba_sdk_template_language_prop__e template_language_prop);

one_msg_waba_sdk_template_language_prop__e template_language_prop_template_language_prop_FromString(char* template_language_prop);

//cJSON *template_language_prop_template_language_prop_convertToJSON(one_msg_waba_sdk_template_language_prop__e template_language_prop);

//one_msg_waba_sdk_template_language_prop__e template_language_prop_template_language_prop_parseFromJSON(cJSON *template_language_propJSON);

#endif /* _template_language_prop_H_ */

