/**
 * one_msg_waba_sdk
 * [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter 'token' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All 'send' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: hello@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.0.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MediaApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_MediaApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_MediaApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/MediaId.h"
#include "CppRestOpenAPIClient/model/UploadMedia.h"
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  MediaApi 
{
public:

    explicit MediaApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~MediaApi();

    /// <summary>
    /// Upload media &amp; get mediaId
    /// </summary>
    /// <remarks>
    /// Upload media and get mediaId. Uploaded media can be sent in template
    /// </remarks>
    /// <param name="uploadMedia"></param>
    pplx::task<std::shared_ptr<MediaId>> uploadMedia(
        std::shared_ptr<UploadMedia> uploadMedia
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_MediaApi_H_ */

