/**
 * one_msg_waba_sdk
 * [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter 'token' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All 'send' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: hello@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.0.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WebhooksApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_WebhooksApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_WebhooksApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/GetAckInfo.h"
#include "CppRestOpenAPIClient/model/GetMe_401_response.h"
#include "CppRestOpenAPIClient/model/SetWebhookStatus.h"
#include "CppRestOpenAPIClient/model/WebhookUrl.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  WebhooksApi 
{
public:

    explicit WebhooksApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~WebhooksApi();

    /// <summary>
    /// Check ACKs
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="messageId">Message ID. Example: 0XzkmGNn4prUAQlzsHApGNRXQ0U</param>
    pplx::task<std::shared_ptr<GetAckInfo>> ackHookInfo(
        utility::string_t messageId
    ) const;
    /// <summary>
    /// Set webhook
    /// </summary>
    /// <remarks>
    /// Sets the URL for receiving webhook notifications of new messages and message delivery events (ack).  **API responses in \&quot;Callbacks\&quot; tab**
    /// </remarks>
    /// <param name="webhookUrl"></param>
    pplx::task<std::shared_ptr<SetWebhookStatus>> setWebhook(
        std::shared_ptr<WebhookUrl> webhookUrl
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_WebhooksApi_H_ */

