/* tslint:disable */
/* eslint-disable */
/**
 * one_msg_waba_sdk
 * [1MSG.IO](https://1msg.io/) is the perfect WhatsApp management tool for your business. With us you get full access to the official Whatsapp API/webhooks.  Every API request must contain an Authorize HTTP header with a token.  This is your channel token, which can be found in your channel project on your profile page. Please do not give the token to anyone or post it publicly.  The authorization token must be added to each request in the GET parameter \'token\' and always passed to query string (?token={your_token}). Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body.   All \'send\' methods (except /sendTemplate) will only work when the dialog session with the user is open. Some of our solutions simplify and avoid such limitations, but we urge you to pay more attention to this detail
 *
 * The version of the OpenAPI document: 2.39.0
 * Contact: hello@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SendProductRequestAllOfAction } from './SendProductRequestAllOfAction';
import {
    SendProductRequestAllOfActionFromJSON,
    SendProductRequestAllOfActionFromJSONTyped,
    SendProductRequestAllOfActionToJSON,
} from './SendProductRequestAllOfAction';

/**
 * 
 * @export
 * @interface SendProductRequest
 */
export interface SendProductRequest {
    /**
     * **Required if phone is not set**
     * 
     * Chat ID from the message list. Examples: 12020721369@c.us
     * . Used instead of the phone parameter.
     * @type {string}
     * @memberof SendProductRequest
     */
    chatId?: string;
    /**
     * **Required if chatId is not set**
     * 
     * A phone number starting with the country code. You do not
     * need to add your number. 
     * 
     * USA example: 12020721369.
     * @type {number}
     * @memberof SendProductRequest
     */
    phone?: number;
    /**
     * 
     * @type {SendProductRequestAllOfAction}
     * @memberof SendProductRequest
     */
    action: SendProductRequestAllOfAction;
    /**
     * Text of message. Example: Some text.
     * @type {string}
     * @memberof SendProductRequest
     */
    body?: string;
    /**
     * Located under the message text. Example: Footer.
     * @type {string}
     * @memberof SendProductRequest
     */
    footer?: string;
    /**
     * Header of catalog. Example: Header.
     * 
     * **Required when sending the catalog.**
     * @type {string}
     * @memberof SendProductRequest
     */
    header?: string;
}

/**
 * Check if a given object implements the SendProductRequest interface.
 */
export function instanceOfSendProductRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;

    return isInstance;
}

export function SendProductRequestFromJSON(json: any): SendProductRequest {
    return SendProductRequestFromJSONTyped(json, false);
}

export function SendProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendProductRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chatId': !exists(json, 'chatId') ? undefined : json['chatId'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'action': SendProductRequestAllOfActionFromJSON(json['action']),
        'body': !exists(json, 'body') ? undefined : json['body'],
        'footer': !exists(json, 'footer') ? undefined : json['footer'],
        'header': !exists(json, 'header') ? undefined : json['header'],
    };
}

export function SendProductRequestToJSON(value?: SendProductRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chatId': value.chatId,
        'phone': value.phone,
        'action': SendProductRequestAllOfActionToJSON(value.action),
        'body': value.body,
        'footer': value.footer,
        'header': value.header,
    };
}

